Repository Team-SIGNAL/SIGNAL-ANDROID, pull requests merged in 2023-12, with the labels that each got.

#133 🔀 :: (#132) 댓글 더보기 제거 및 날짜 수정
  presentation/src/main/java/com/signal/signal_android/feature/main/feed/CommentDialog.kt
  presentation/src/main/java/com/signal/signal_android/feature/main/feed/FeedViewModel.kt
  presentation/src/main/res/values/strings.xml
Labels: 기능 구현, 리팩토링

#137 🔀 :: (#136) 업적 수정
  presentation/src/main/java/com/signal/signal_android/feature/main/mypage/MyPage.kt
  presentation/src/main/res/values/strings.xml
Labels: 기능 구현

#138 🔀 :: (#83) 프로필 사진 수정 기능 구현
  data/src/main/kotlin/com/signal/data/api/SignalUrl.kt
  data/src/main/kotlin/com/signal/data/api/UserApi.kt
  data/src/main/kotlin/com/signal/data/datasource/user/remote/RemoteUserDataSource.kt
  data/src/main/kotlin/com/signal/data/datasource/user/remote/RemoteUserDataSourceImpl.kt
  data/src/main/kotlin/com/signal/data/model/mypage/EditProfileRequest.kt
  data/src/main/kotlin/com/signal/data/repository/UserRepositoryImpl.kt
  domain/src/main/kotlin/com/signal/domain/repository/UserRepository.kt
  presentation/src/main/java/com/signal/signal_android/SignalApp.kt
  presentation/src/main/java/com/signal/signal_android/SignalApplication.kt
  presentation/src/main/java/com/signal/signal_android/feature/main/Main.kt
  presentation/src/main/java/com/signal/signal_android/feature/main/mypage/EditProfile.kt
  presentation/src/main/java/com/signal/signal_android/feature/main/mypage/MyPage.kt
  presentation/src/main/java/com/signal/signal_android/feature/main/mypage/MyPageSideEffect.kt
  presentation/src/main/java/com/signal/signal_android/feature/main/mypage/MyPageViewModel.kt
  presentation/src/main/java/com/signal/signal_android/navigation/MainNavigation.kt
  presentation/src/main/java/com/signal/signal_android/navigation/NavigationRoute.kt
  presentation/src/main/res/values/strings.xml
Labels: 기능 구현

#140 🔀 :: (#139) room unique id 오류 해결
  data/src/main/kotlin/com/signal/data/dao/DiagnosisDao.kt
  data/src/main/kotlin/com/signal/data/datasource/diagnosis/LocalDiagnosisDataSource.kt
  data/src/main/kotlin/com/signal/data/datasource/diagnosis/LocalDiagnosisDataSourceImpl.kt
  data/src/main/kotlin/com/signal/data/repository/DiagnosisRepositoryImpl.kt
  domain/src/main/kotlin/com/signal/domain/repository/DiagnosisRepository.kt
  domain/src/main/kotlin/com/signal/domain/usecase/users/GetHistoryCountUseCase.kt
  presentation/src/main/java/com/signal/signal_android/SignalApplication.kt
  presentation/src/main/java/com/signal/signal_android/feature/diagnosis/DiagnosisState.kt
  presentation/src/main/java/com/signal/signal_android/feature/diagnosis/DiagnosisViewModel.kt
Labels: 기능 구현

#147 🔀 :: (#141) 병원 진료 예약 코드 리팩토링
  presentation/src/main/java/com/signal/signal_android/feature/reservation/Reservation.kt
  presentation/src/main/java/com/signal/signal_android/feature/reservation/ReservationState.kt
  presentation/src/main/java/com/signal/signal_android/feature/reservation/ReservationViewModel.kt
Labels: 리팩토링

#144 🔀 :: (#117) 커뮤니티 신고 기능 구현
  data/src/main/kotlin/com/signal/data/api/FeedApi.kt
  data/src/main/kotlin/com/signal/data/api/SignalUrl.kt
  data/src/main/kotlin/com/signal/data/datasource/feed/FeedDataSource.kt
  data/src/main/kotlin/com/signal/data/datasource/feed/FeedDataSourceImpl.kt
  data/src/main/kotlin/com/signal/data/repository/FeedRepositoryImpl.kt
  domain/src/main/kotlin/com/signal/domain/repository/FeedRepository.kt
  presentation/src/main/java/com/signal/signal_android/SignalApp.kt
  presentation/src/main/java/com/signal/signal_android/feature/main/Main.kt
  presentation/src/main/java/com/signal/signal_android/feature/main/feed/Feed.kt
  presentation/src/main/java/com/signal/signal_android/feature/main/feed/FeedSideEffect.kt
  presentation/src/main/java/com/signal/signal_android/feature/main/feed/FeedViewModel.kt
  presentation/src/main/java/com/signal/signal_android/feature/main/home/Home.kt
  presentation/src/main/java/com/signal/signal_android/navigation/MainNavigation.kt
  presentation/src/main/res/values/strings.xml
Labels: 기능 구현

#146 🔀 :: (#145) qa 버그
  presentation/src/main/java/com/signal/signal_android/feature/main/diary/AllDiary.kt
  presentation/src/main/java/com/signal/signal_android/feature/main/diary/CreateDiary.kt
  presentation/src/main/java/com/signal/signal_android/feature/main/diary/DiaryState.kt
  presentation/src/main/java/com/signal/signal_android/feature/main/diary/DiaryViewModel.kt
  presentation/src/main/java/com/signal/signal_android/feature/main/feed/CommentDialog.kt
  presentation/src/main/java/com/signal/signal_android/feature/main/home/Home.kt
  presentation/src/main/java/com/signal/signal_android/feature/main/mypage/MyPage.kt
Labels: 버그!, 리팩토링

#151 🔀 :: (#150) 추천 카테고리 로직 버그 수정
  presentation/src/main/java/com/signal/signal_android/feature/main/recommend/Recommend.kt
  presentation/src/main/java/com/signal/signal_android/feature/main/recommend/Recommends.kt
  presentation/src/main/java/com/signal/signal_android/navigation/MainNavigation.kt
  presentation/src/main/java/com/signal/signal_android/navigation/NavigationRoute.kt
  presentation/src/main/res/values/strings.xml
Labels: 버그!

#153 🔀 :: (#152) 진료 예약 날짜 오류 수정
  presentation/src/main/java/com/signal/signal_android/feature/reservation/CreateReservation.kt
  presentation/src/main/java/com/signal/signal_android/feature/reservation/Reservation.kt
Labels: 버그!, 리팩토링

#155 🔀 :: (#154) 검색 기능 삭제
  presentation/src/main/java/com/signal/signal_android/feature/main/feed/Feed.kt
  presentation/src/main/java/com/signal/signal_android/feature/main/feed/FeedDetails.kt
  presentation/src/main/java/com/signal/signal_android/feature/main/mypage/EditProfile.kt
Labels: 리팩토링

#158 🔀 :: (#156) 우울증 수치 정보 구현
  presentation/src/main/java/com/signal/signal_android/designsystem/foundation/SignalColor.kt
  presentation/src/main/java/com/signal/signal_android/feature/main/diary/Diary.kt
  presentation/src/main/java/com/signal/signal_android/feature/main/home/Home.kt
  presentation/src/main/res/values/strings.xml
Labels: 기능 구현

#159 🔀 :: (#157) 피드 이미지 수정 안됨
  presentation/src/main/java/com/signal/signal_android/feature/bug/ReportBug.kt
  presentation/src/main/java/com/signal/signal_android/feature/main/feed/CreatePost.kt
  presentation/src/main/java/com/signal/signal_android/feature/main/feed/FeedViewModel.kt
Labels: 버그!
