Repository Team-SIGNAL/SIGNAL-ANDROID, pull requests merged in 2023-10, with the labels that each got.

#11 🔀 :: (#8) 회원가입 퍼블리싱
  domain/src/main/kotlin/com/signal/domain/enums/Gender.kt
  presentation/build.gradle.kts
  presentation/src/main/java/com/signal/signal_android/SignalApp.kt
  presentation/src/main/java/com/signal/signal_android/designsystem/component/SignUpTitle.kt
  presentation/src/main/java/com/signal/signal_android/designsystem/radiobutton/SignalRadioButton.kt
  presentation/src/main/java/com/signal/signal_android/feature/landing/Landing.kt
  presentation/src/main/java/com/signal/signal_android/feature/signin/SignIn.kt
  presentation/src/main/java/com/signal/signal_android/feature/signup/SignUpAccount.kt
  presentation/src/main/java/com/signal/signal_android/feature/signup/SignUpUser.kt
  presentation/src/main/java/com/signal/signal_android/navigation/AuthNavigation.kt
  presentation/src/main/java/com/signal/signal_android/navigation/NavigationRoute.kt
  presentation/src/main/java/com/signal/signal_android/navigation/UserNavigation.kt
  presentation/src/main/res/values/strings.xml
Labels: 기능 구현

#16 🔀 :: (#15) ci 구축
  .github/workflows/android.yml
Labels: 프로젝트 세팅

#13 🔀 :: (#12) 로그인 서버 연동
  data/build.gradle.kts
  data/src/main/kotlin/com/signal/data/api/ApiProvider.kt
  data/src/main/kotlin/com/signal/data/api/SignalUrl.kt
  data/src/main/kotlin/com/signal/data/api/UserApi.kt
  data/src/main/kotlin/com/signal/data/datasource/user/local/LocalUserDataSource.kt
  data/src/main/kotlin/com/signal/data/datasource/user/local/LocalUserDataSourceImpl.kt
  data/src/main/kotlin/com/signal/data/datasource/user/remote/RemoteUserDataSource.kt
  data/src/main/kotlin/com/signal/data/datasource/user/remote/RemoteUserDataSourceImpl.kt
  data/src/main/kotlin/com/signal/data/model/signin/SignInRequest.kt
  data/src/main/kotlin/com/signal/data/model/signin/SignInResponse.kt
  data/src/main/kotlin/com/signal/data/repository/UserRepositoryImpl.kt
  data/src/main/kotlin/com/signal/data/util/ExceptionHandler.kt
  data/src/main/kotlin/com/signal/data/util/TokenInterceptor.kt
  domain/src/main/kotlin/com/signal/domain/exception/Exceptions.kt
  domain/src/main/kotlin/com/signal/domain/repository/UserRepository.kt
  domain/src/main/kotlin/com/signal/domain/usecase/SignInUseCase.kt
  presentation/build.gradle.kts
  presentation/src/main/AndroidManifest.xml
  presentation/src/main/java/com/signal/signal_android/SignalApplication.kt
  presentation/src/main/java/com/signal/signal_android/designsystem/textfield/SignalTextField.kt
  presentation/src/main/java/com/signal/signal_android/feature/signin/SignIn.kt
  presentation/src/main/java/com/signal/signal_android/feature/signin/SignInSideEffect.kt
  presentation/src/main/java/com/signal/signal_android/feature/signin/SignInState.kt
  presentation/src/main/java/com/signal/signal_android/viewmodel/BaseViewModel.kt
  presentation/src/main/java/com/signal/signal_android/viewmodel/SignInViewModel.kt
  presentation/src/main/res/drawable/ic_visible_off.xml
  presentation/src/main/res/drawable/ic_visible_on.xml
  presentation/src/main/res/values/strings.xml
  settings.gradle.kts
Labels: 기능 구현

#17 🔀 :: (#14) 회원가입 서버 연동
  data/src/main/kotlin/com/signal/data/api/SignalUrl.kt
  data/src/main/kotlin/com/signal/data/api/UserApi.kt
  data/src/main/kotlin/com/signal/data/datasource/user/remote/RemoteUserDataSource.kt
  data/src/main/kotlin/com/signal/data/datasource/user/remote/RemoteUserDataSourceImpl.kt
  data/src/main/kotlin/com/signal/data/model/signup/SignUpRequest.kt
  data/src/main/kotlin/com/signal/data/repository/UserRepositoryImpl.kt
  domain/src/main/java/com/signal/signal_android/domain/regex/Regexs.kt
  domain/src/main/kotlin/com/signal/domain/repository/UserRepository.kt
  domain/src/main/kotlin/com/signal/domain/usecase/users/SignInUseCase.kt
  domain/src/main/kotlin/com/signal/domain/usecase/users/SignUpUseCase.kt
  presentation/src/main/java/com/signal/signal_android/SignalApplication.kt
  presentation/src/main/java/com/signal/signal_android/designsystem/textfield/SignalTextField.kt
  presentation/src/main/java/com/signal/signal_android/feature/signin/SignIn.kt
  presentation/src/main/java/com/signal/signal_android/feature/signup/SignUpAccount.kt
  presentation/src/main/java/com/signal/signal_android/feature/signup/SignUpSideEffect.kt
  presentation/src/main/java/com/signal/signal_android/feature/signup/SignUpState.kt
  presentation/src/main/java/com/signal/signal_android/feature/signup/SignUpUser.kt
  presentation/src/main/java/com/signal/signal_android/feature/signup/SignUpViewModel.kt
  presentation/src/main/java/com/signal/signal_android/navigation/AuthNavigation.kt
  presentation/src/main/java/com/signal/signal_android/viewmodel/BaseViewModel.kt
  presentation/src/main/java/com/signal/signal_android/viewmodel/SignInViewModel.kt
  presentation/src/main/res/drawable/ic_calendar.xml
  presentation/src/main/res/values/strings.xml
Labels: 기능 구현

#18 🔀 :: (#9) 마이페이지 퍼블리싱
  presentation/src/main/java/com/signal/signal_android/SignalApp.kt
  presentation/src/main/java/com/signal/signal_android/designsystem/foundation/Color.kt
  presentation/src/main/java/com/signal/signal_android/feature/mypage/MyPage.kt
  presentation/src/main/java/com/signal/signal_android/navigation/NavigationRoute.kt
  presentation/src/main/java/com/signal/signal_android/navigation/UserNavigation.kt
  presentation/src/main/res/drawable/ic_add_image.png
  presentation/src/main/res/drawable/ic_bug.png
  presentation/src/main/res/drawable/ic_delete_account.png
  presentation/src/main/res/drawable/ic_logout.png
  presentation/src/main/res/drawable/ic_next_gray.png
  presentation/src/main/res/drawable/ic_profile_image.png
  presentation/src/main/res/values/strings.xml
Labels: 기능 구현

#22 🔀 :: (#21) 디자인 시스템 리팩토링
  build.gradle.kts
  data/build.gradle.kts
  data/src/main/kotlin/com/signal/data/api/ApiProvider.kt
  data/src/main/kotlin/com/signal/data/api/SignalUrl.kt
  data/src/main/kotlin/com/signal/data/api/UserApi.kt
  data/src/main/kotlin/com/signal/data/datasource/user/local/LocalUserDataSource.kt
  data/src/main/kotlin/com/signal/data/datasource/user/remote/RemoteUserDataSource.kt
  data/src/main/kotlin/com/signal/data/datasource/user/remote/RemoteUserDataSourceImpl.kt
  data/src/main/kotlin/com/signal/data/model/signin/SignInRequest.kt
  data/src/main/kotlin/com/signal/data/model/signin/SignInResponse.kt
  data/src/main/kotlin/com/signal/data/model/signup/SignUpRequest.kt
  data/src/main/kotlin/com/signal/data/repository/UserRepositoryImpl.kt
  data/src/main/kotlin/com/signal/data/util/ExceptionHandler.kt
  data/src/main/kotlin/com/signal/data/util/TokenInterceptor.kt
  di/build.gradle.kts
  domain/build.gradle.kts
  domain/src/androidTest/java/com/signal/domain/ExampleInstrumentedTest.kt
  domain/src/main/java/com/signal/signal_android/domain/regex/Regexs.kt
  domain/src/main/kotlin/com/signal/domain/enums/Gender.kt
  domain/src/main/kotlin/com/signal/domain/exception/Exceptions.kt
  domain/src/main/kotlin/com/signal/domain/repository/UserRepository.kt
  domain/src/main/kotlin/com/signal/domain/usecase/users/SignInUseCase.kt
  domain/src/main/kotlin/com/signal/domain/usecase/users/SignUpUseCase.kt
  presentation/build.gradle.kts
  presentation/src/main/java/com/signal/signal_android/SignalApp.kt
  presentation/src/main/java/com/signal/signal_android/SignalApplication.kt
  presentation/src/main/java/com/signal/signal_android/designsystem/button/BasicButton.kt
  presentation/src/main/java/com/signal/signal_android/designsystem/color/SignalButtonColor.kt
  presentation/src/main/java/com/signal/signal_android/designsystem/color/SignalTextFieldColor.kt
  presentation/src/main/java/com/signal/signal_android/designsystem/component/Indicator.kt
  presentation/src/main/java/com/signal/signal_android/designsystem/component/SignUpTitle.kt
  presentation/src/main/java/com/signal/signal_android/designsystem/foundation/SignalColor.kt
  presentation/src/main/java/com/signal/signal_android/designsystem/foundation/Theme.kt
  presentation/src/main/java/com/signal/signal_android/designsystem/foundation/Typography.kt
  presentation/src/main/java/com/signal/signal_android/designsystem/radiobutton/SignalRadioButton.kt
  presentation/src/main/java/com/signal/signal_android/designsystem/textfield/SignalTextField.kt
  presentation/src/main/java/com/signal/signal_android/designsystem/util/SignalClickable.kt
  presentation/src/main/java/com/signal/signal_android/feature/landing/Landing.kt
  presentation/src/main/java/com/signal/signal_android/feature/mypage/MyPage.kt
  presentation/src/main/java/com/signal/signal_android/feature/signin/SignIn.kt
  presentation/src/main/java/com/signal/signal_android/feature/signin/SignInSideEffect.kt
  presentation/src/main/java/com/signal/signal_android/feature/signin/SignInState.kt
  presentation/src/main/java/com/signal/signal_android/feature/signup/SignUpAccount.kt
  presentation/src/main/java/com/signal/signal_android/feature/signup/SignUpSideEffect.kt
  presentation/src/main/java/com/signal/signal_android/feature/signup/SignUpState.kt
  presentation/src/main/java/com/signal/signal_android/feature/signup/SignUpUser.kt
  presentation/src/main/java/com/signal/signal_android/feature/signup/SignUpViewModel.kt
  presentation/src/main/java/com/signal/signal_android/feature/splash/Splash.kt
  presentation/src/main/java/com/signal/signal_android/navigation/AuthNavigation.kt
  presentation/src/main/java/com/signal/signal_android/navigation/NavigationRoute.kt
  presentation/src/main/java/com/signal/signal_android/navigation/UserNavigation.kt
  presentation/src/main/java/com/signal/signal_android/viewmodel/SignInViewModel.kt
Labels: 리팩토링

#24 🔀 :: (#23) 바텀 내비게이션 구현
  presentation/build.gradle.kts
  presentation/src/main/java/com/signal/signal_android/SignalApp.kt
  presentation/src/main/java/com/signal/signal_android/designsystem/component/NavigationItem.kt
  presentation/src/main/java/com/signal/signal_android/designsystem/component/SignalBottomBar.kt
  presentation/src/main/java/com/signal/signal_android/feature/main/Main.kt
  presentation/src/main/java/com/signal/signal_android/feature/main/diary/Diary.kt
  presentation/src/main/java/com/signal/signal_android/feature/main/feed/Feed.kt
  presentation/src/main/java/com/signal/signal_android/feature/main/home/Home.kt
  presentation/src/main/java/com/signal/signal_android/feature/main/recommend/Recommend.kt
  presentation/src/main/java/com/signal/signal_android/navigation/MainNavigation.kt
  presentation/src/main/java/com/signal/signal_android/navigation/NavigationRoute.kt
  presentation/src/main/res/drawable/ic_diary.xml
  presentation/src/main/res/drawable/ic_feed.xml
  presentation/src/main/res/drawable/ic_home.xml
  presentation/src/main/res/drawable/ic_my_page.xml
  presentation/src/main/res/drawable/ic_recommend.xml
  presentation/src/main/res/values/strings.xml
Labels: 기능 구현

#29 🔀 :: (#19) 로그아웃 회원탈퇴 기능 구현
  data/src/main/kotlin/com/signal/data/api/SignalUrl.kt
  data/src/main/kotlin/com/signal/data/api/UserApi.kt
  data/src/main/kotlin/com/signal/data/datasource/user/local/LocalUserDataSource.kt
  data/src/main/kotlin/com/signal/data/datasource/user/local/LocalUserDataSourceImpl.kt
  data/src/main/kotlin/com/signal/data/datasource/user/remote/RemoteUserDataSource.kt
  data/src/main/kotlin/com/signal/data/datasource/user/remote/RemoteUserDataSourceImpl.kt
  data/src/main/kotlin/com/signal/data/repository/UserRepositoryImpl.kt
  domain/src/main/kotlin/com/signal/domain/repository/UserRepository.kt
  domain/src/main/kotlin/com/signal/domain/usecase/users/SecessionUseCase.kt
  domain/src/main/kotlin/com/signal/domain/usecase/users/SignOutUseCase.kt
  presentation/build.gradle.kts
  presentation/src/main/java/com/signal/signal_android/SignalApp.kt
  presentation/src/main/java/com/signal/signal_android/SignalApplication.kt
  presentation/src/main/java/com/signal/signal_android/feature/main/Main.kt
  presentation/src/main/java/com/signal/signal_android/feature/mypage/MyPage.kt
  presentation/src/main/java/com/signal/signal_android/feature/mypage/MyPageSideEffect.kt
  presentation/src/main/java/com/signal/signal_android/feature/mypage/MyPageState.kt
  presentation/src/main/java/com/signal/signal_android/feature/mypage/MyPageViewModel.kt
  presentation/src/main/java/com/signal/signal_android/navigation/MainNavigation.kt
  presentation/src/main/java/com/signal/signal_android/navigation/UserNavigation.kt
  presentation/src/main/res/values/strings.xml
Labels: 기능 구현

#30 🔗 :: (#28) 커뮤니티 퍼블리싱
  presentation/build.gradle.kts
  presentation/src/main/AndroidManifest.xml
  presentation/src/main/java/com/signal/signal_android/MainActivity.kt
  presentation/src/main/java/com/signal/signal_android/SignalApp.kt
  presentation/src/main/java/com/signal/signal_android/designsystem/button/BasicButton.kt
  presentation/src/main/java/com/signal/signal_android/designsystem/component/Header.kt
  presentation/src/main/java/com/signal/signal_android/designsystem/component/SignalDialog.kt
  presentation/src/main/java/com/signal/signal_android/designsystem/textfield/SignalTextField.kt
  presentation/src/main/java/com/signal/signal_android/feature/main/Main.kt
  presentation/src/main/java/com/signal/signal_android/feature/main/feed/CommentDialog.kt
  presentation/src/main/java/com/signal/signal_android/feature/main/feed/Feed.kt
  presentation/src/main/java/com/signal/signal_android/feature/main/feed/FeedDetails.kt
  presentation/src/main/java/com/signal/signal_android/feature/mypage/MyPage.kt
  presentation/src/main/java/com/signal/signal_android/navigation/MainNavigation.kt
  presentation/src/main/java/com/signal/signal_android/navigation/NavigationRoute.kt
  presentation/src/main/res/drawable/ic_back.xml
  presentation/src/main/res/drawable/ic_edit.xml
  presentation/src/main/res/drawable/ic_more.xml
  presentation/src/main/res/values/strings.xml
Labels: 기능 구현

#32 🔀 :: (#26) viewmodel 패키지 이동
  presentation/src/main/java/com/signal/signal_android/BaseViewModel.kt
  presentation/src/main/java/com/signal/signal_android/SignalApplication.kt
  presentation/src/main/java/com/signal/signal_android/feature/mypage/MyPageViewModel.kt
  presentation/src/main/java/com/signal/signal_android/feature/signin/SignIn.kt
  presentation/src/main/java/com/signal/signal_android/feature/signin/SignInViewModel.kt
  presentation/src/main/java/com/signal/signal_android/feature/signup/SignUpViewModel.kt
Labels: 리팩토링

#34 🔀 :: (#33) 커뮤니티 작성 퍼블리싱
  presentation/src/main/java/com/signal/signal_android/SignalApp.kt
  presentation/src/main/java/com/signal/signal_android/designsystem/component/Header.kt
  presentation/src/main/java/com/signal/signal_android/designsystem/textfield/SignalTextField.kt
  presentation/src/main/java/com/signal/signal_android/feature/main/Main.kt
  presentation/src/main/java/com/signal/signal_android/feature/main/feed/CreatePost.kt
  presentation/src/main/java/com/signal/signal_android/feature/main/feed/Feed.kt
  presentation/src/main/java/com/signal/signal_android/feature/main/feed/FeedDetails.kt
  presentation/src/main/java/com/signal/signal_android/navigation/MainNavigation.kt
  presentation/src/main/java/com/signal/signal_android/navigation/NavigationRoute.kt
  presentation/src/main/res/drawable/ic_gallery.xml
  presentation/src/main/res/values/strings.xml
Labels: 기능 구현

#35 🔀 :: (#20) 마이페이지 내 정보 조회 기능 구현
  data/src/main/kotlin/com/signal/data/api/SignalUrl.kt
  data/src/main/kotlin/com/signal/data/api/UserApi.kt
  data/src/main/kotlin/com/signal/data/datasource/user/remote/RemoteUserDataSource.kt
  data/src/main/kotlin/com/signal/data/datasource/user/remote/RemoteUserDataSourceImpl.kt
  data/src/main/kotlin/com/signal/data/model/mypage/FetchUserInformationResponse.kt
  data/src/main/kotlin/com/signal/data/repository/UserRepositoryImpl.kt
  domain/src/main/kotlin/com/signal/domain/repository/UserRepository.kt
  domain/src/main/kotlin/com/signal/domain/usecase/users/FetchUserInformationUseCase.kt
  presentation/src/main/java/com/signal/signal_android/SignalApp.kt
  presentation/src/main/java/com/signal/signal_android/SignalApplication.kt
  presentation/src/main/java/com/signal/signal_android/feature/mypage/MyPage.kt
  presentation/src/main/java/com/signal/signal_android/feature/mypage/MyPageState.kt
  presentation/src/main/java/com/signal/signal_android/feature/mypage/MyPageViewModel.kt
  presentation/src/main/res/values/strings.xml
Labels: 기능 구현

#38 🔀 :: (#36) 커뮤니티 신고 퍼블리싱
  presentation/src/main/java/com/signal/signal_android/SignalApp.kt
  presentation/src/main/java/com/signal/signal_android/designsystem/dropdown/SignalDropDown.kt
  presentation/src/main/java/com/signal/signal_android/feature/main/Main.kt
  presentation/src/main/java/com/signal/signal_android/feature/main/feed/Feed.kt
  presentation/src/main/java/com/signal/signal_android/feature/main/feed/Report.kt
  presentation/src/main/java/com/signal/signal_android/navigation/MainNavigation.kt
  presentation/src/main/java/com/signal/signal_android/navigation/NavigationRoute.kt
  presentation/src/main/res/drawable/ic_down.xml
  presentation/src/main/res/values/strings.xml
Labels: 기능 구현

#39 🔀 ;: (#37) 바텀 내비게이션 클릭 시 아이콘 변경
  presentation/src/main/java/com/signal/signal_android/designsystem/component/NavigationItem.kt
  presentation/src/main/java/com/signal/signal_android/designsystem/component/SignalBottomBar.kt
  presentation/src/main/res/drawable/ic_diary_filled.xml
  presentation/src/main/res/drawable/ic_diary_outlined.xml
  presentation/src/main/res/drawable/ic_feed_filled.xml
  presentation/src/main/res/drawable/ic_feed_outlined.xml
  presentation/src/main/res/drawable/ic_home_filled.xml
  presentation/src/main/res/drawable/ic_home_outlined.xml
  presentation/src/main/res/drawable/ic_my_page_filled.xml
  presentation/src/main/res/drawable/ic_my_page_outlined.xml
  presentation/src/main/res/drawable/ic_recommend_filled.xml
  presentation/src/main/res/drawable/ic_recommend_outlined.xml
Labels: 리팩토링
