Repository Team-SIGNAL/SIGNAL-ANDROID, pull requests merged in 2023-11, with the labels that each got.

#40 🔀 :: (#25) 서버 로직 테스트
  data/build.gradle.kts
  data/src/main/kotlin/com/signal/data/api/ApiProvider.kt
  data/src/main/kotlin/com/signal/data/api/UserApi.kt
  data/src/main/kotlin/com/signal/data/datasource/user/local/LocalUserDataSource.kt
  data/src/main/kotlin/com/signal/data/datasource/user/local/LocalUserDataSourceImpl.kt
  data/src/main/kotlin/com/signal/data/model/signin/SignInResponse.kt
  data/src/main/kotlin/com/signal/data/model/signup/SignUpRequest.kt
  data/src/main/kotlin/com/signal/data/repository/UserRepositoryImpl.kt
  domain/src/main/kotlin/com/signal/domain/enums/Gender.kt
  domain/src/main/kotlin/com/signal/domain/repository/UserRepository.kt
  domain/src/main/kotlin/com/signal/domain/usecase/users/SignUpUseCase.kt
  presentation/src/main/AndroidManifest.xml
  presentation/src/main/java/com/signal/signal_android/BaseViewModel.kt
  presentation/src/main/java/com/signal/signal_android/SignalApp.kt
  presentation/src/main/java/com/signal/signal_android/feature/signin/SignIn.kt
  presentation/src/main/java/com/signal/signal_android/feature/signin/SignInViewModel.kt
  presentation/src/main/java/com/signal/signal_android/feature/signup/SignUpAccount.kt
  presentation/src/main/java/com/signal/signal_android/feature/signup/SignUpState.kt
  presentation/src/main/java/com/signal/signal_android/feature/signup/SignUpUser.kt
  presentation/src/main/java/com/signal/signal_android/feature/signup/SignUpViewModel.kt
  presentation/src/main/java/com/signal/signal_android/navigation/AuthNavigation.kt
Labels: 버그!, 리팩토링

#41 🔀 :: (#27) 홈 퍼블리싱
  presentation/build.gradle.kts
  presentation/src/main/java/com/signal/signal_android/feature/main/home/Home.kt
  presentation/src/main/res/values/strings.xml
Labels: 기능 구현

#44 🔀 :: (#43) 토큰 bearer 추가
  data/src/main/kotlin/com/signal/data/util/TokenInterceptor.kt
Labels: 리팩토링

#48 🔀 :: (#46) navigation 로직 버그 수정
  presentation/src/main/java/com/signal/signal_android/MainActivity.kt
  presentation/src/main/java/com/signal/signal_android/SignalApp.kt
  presentation/src/main/java/com/signal/signal_android/feature/signin/SignInViewModel.kt
  presentation/src/main/res/values/strings.xml
Labels: 리팩토링

#47 🔀 :: (#45) 회원탈퇴 로직 수정
  data/src/main/kotlin/com/signal/data/api/UserApi.kt
  presentation/src/main/java/com/signal/signal_android/feature/mypage/MyPageViewModel.kt
Labels: 버그!, 리팩토링

#50 🔀 :: (#49) 컨텐츠 추천 퍼블리싱
  presentation/src/main/java/com/signal/signal_android/feature/main/recommend/Recommend.kt
  presentation/src/main/res/drawable/bg_recommend_exercise.png
  presentation/src/main/res/drawable/bg_recommend_hospital.png
  presentation/src/main/res/drawable/bg_recommend_music.png
  presentation/src/main/res/drawable/bg_recommend_video.png
  presentation/src/main/res/drawable/ic_search.xml
  presentation/src/main/res/values/strings.xml
Labels: 기능 구현

#53 🔀 :: (#51) 마이페이지 내 정보 조회 수정
  data/src/main/kotlin/com/signal/data/model/mypage/FetchUserInformationResponse.kt
  data/src/main/kotlin/com/signal/data/repository/UserRepositoryImpl.kt
  domain/src/main/kotlin/com/signal/domain/entity/UserInformationEntity.kt
  domain/src/main/kotlin/com/signal/domain/repository/UserRepository.kt
  presentation/src/main/java/com/signal/signal_android/feature/mypage/MyPage.kt
  presentation/src/main/java/com/signal/signal_android/feature/mypage/MyPageState.kt
  presentation/src/main/java/com/signal/signal_android/feature/mypage/MyPageViewModel.kt
Labels: 버그!, 리팩토링

#55 🔀 :: (#31) 고민일기 퍼블리싱
  presentation/src/main/java/com/signal/signal_android/SignalApp.kt
  presentation/src/main/java/com/signal/signal_android/feature/main/Main.kt
  presentation/src/main/java/com/signal/signal_android/feature/main/diary/AllDiary.kt
  presentation/src/main/java/com/signal/signal_android/feature/main/diary/CreateDiary.kt
  presentation/src/main/java/com/signal/signal_android/feature/main/diary/Diary.kt
  presentation/src/main/java/com/signal/signal_android/feature/main/diary/DiaryDetail.kt
  presentation/src/main/java/com/signal/signal_android/feature/main/diary/Emotion.kt
  presentation/src/main/java/com/signal/signal_android/feature/main/feed/FeedDetails.kt
  presentation/src/main/java/com/signal/signal_android/navigation/MainNavigation.kt
  presentation/src/main/java/com/signal/signal_android/navigation/NavigationRoute.kt
  presentation/src/main/res/drawable/ic_angry.png
  presentation/src/main/res/drawable/ic_annoying.png
  presentation/src/main/res/drawable/ic_awkwardness.png
  presentation/src/main/res/drawable/ic_boredom.png
  presentation/src/main/res/drawable/ic_depression.png
  presentation/src/main/res/drawable/ic_discomfort.png
  presentation/src/main/res/drawable/ic_happy.png
  presentation/src/main/res/drawable/ic_pleased.png
  presentation/src/main/res/drawable/ic_sadness.png
  presentation/src/main/res/drawable/ic_sobbing.png
  presentation/src/main/res/drawable/ic_soso.png
  presentation/src/main/res/drawable/ic_surprised.png
  presentation/src/main/res/values/strings.xml
Labels: 기능 구현

#56 🔀 :: (#52) 자가진단 퍼블리싱
  presentation/src/main/java/com/signal/signal_android/SignalApp.kt
  presentation/src/main/java/com/signal/signal_android/feature/diagnosis/Diagnosis.kt
  presentation/src/main/java/com/signal/signal_android/feature/diagnosis/DiagnosisComplete.kt
  presentation/src/main/java/com/signal/signal_android/feature/diagnosis/DiagnosisLanding.kt
  presentation/src/main/java/com/signal/signal_android/feature/landing/Landing.kt
  presentation/src/main/java/com/signal/signal_android/feature/main/Main.kt
  presentation/src/main/java/com/signal/signal_android/feature/main/home/Home.kt
  presentation/src/main/java/com/signal/signal_android/navigation/MainNavigation.kt
  presentation/src/main/java/com/signal/signal_android/navigation/NavigationRoute.kt
  presentation/src/main/java/com/signal/signal_android/navigation/UserNavigation.kt
  presentation/src/main/res/drawable/ic_landing_self_diagnosis.png
  presentation/src/main/res/values/strings.xml
Labels: 기능 구현

#59 🔀 :: (#58) room 세팅
  data/build.gradle.kts
  data/src/main/kotlin/com/signal/data/dao/DiagnosisDao.kt
  data/src/main/kotlin/com/signal/data/database/SignalDatabase.kt
  data/src/main/kotlin/com/signal/data/model/diagnosis/DiagnosisEntity.kt
  domain/build.gradle.kts
  presentation/build.gradle.kts
  presentation/src/main/java/com/signal/signal_android/DBInitializer.kt
  presentation/src/main/java/com/signal/signal_android/MainActivity.kt
  presentation/src/main/res/values/strings.xml
Labels: 기능 구현

#57 🔀 :: (#42) 커뮤니티 목록 서버 연동
  data/src/main/kotlin/com/signal/data/api/ApiProvider.kt
  data/src/main/kotlin/com/signal/data/api/FeedApi.kt
  data/src/main/kotlin/com/signal/data/api/SignalUrl.kt
  data/src/main/kotlin/com/signal/data/datasource/feed/FeedDataSource.kt
  data/src/main/kotlin/com/signal/data/datasource/feed/FeedDataSourceImpl.kt
  data/src/main/kotlin/com/signal/data/model/feed/request/PostRequest.kt
  data/src/main/kotlin/com/signal/data/model/feed/response/FetchPostDetailsResponse.kt
  data/src/main/kotlin/com/signal/data/model/feed/response/FetchPostsResponse.kt
  data/src/main/kotlin/com/signal/data/repository/FeedRepositoryImpl.kt
  data/src/main/kotlin/com/signal/data/util/TokenInterceptor.kt
  domain/src/main/kotlin/com/signal/domain/PostsEntity.kt
  domain/src/main/kotlin/com/signal/domain/entity/PostDetailsEntity.kt
  domain/src/main/kotlin/com/signal/domain/enums/Tag.kt
  domain/src/main/kotlin/com/signal/domain/repository/FeedRepository.kt
  presentation/src/main/java/com/signal/signal_android/SignalApplication.kt
  presentation/src/main/java/com/signal/signal_android/feature/main/feed/CreatePost.kt
  presentation/src/main/java/com/signal/signal_android/feature/main/feed/Feed.kt
  presentation/src/main/java/com/signal/signal_android/feature/main/feed/FeedDetails.kt
  presentation/src/main/java/com/signal/signal_android/feature/main/feed/FeedSideEffect.kt
  presentation/src/main/java/com/signal/signal_android/feature/main/feed/FeedState.kt
  presentation/src/main/java/com/signal/signal_android/feature/main/feed/FeedViewModel.kt
  presentation/src/main/res/values/strings.xml
Labels: 기능 구현

#61 🔀 :: (#54) 병원 진료 예약 퍼블리싱
  presentation/src/main/java/com/signal/signal_android/SignalApp.kt
  presentation/src/main/java/com/signal/signal_android/feature/main/Main.kt
  presentation/src/main/java/com/signal/signal_android/feature/main/home/Home.kt
  presentation/src/main/java/com/signal/signal_android/feature/main/reservation/CreateReservation.kt
  presentation/src/main/java/com/signal/signal_android/feature/main/reservation/Hospital.kt
  presentation/src/main/java/com/signal/signal_android/feature/main/reservation/Reservation.kt
  presentation/src/main/java/com/signal/signal_android/navigation/MainNavigation.kt
  presentation/src/main/java/com/signal/signal_android/navigation/NavigationRoute.kt
  presentation/src/main/res/drawable/ic_default_hospital.png
  presentation/src/main/res/values/strings.xml
Labels: 기능 구현

#64 🔀 :: (#62) 자가진단 room 연결
  data/src/main/kotlin/com/signal/data/dao/DiagnosisDao.kt
  data/src/main/kotlin/com/signal/data/database/SignalDatabase.kt
  data/src/main/kotlin/com/signal/data/datasource/diagnosis/LocalDiagnosisDataSource.kt
  data/src/main/kotlin/com/signal/data/datasource/diagnosis/LocalDiagnosisDataSourceImpl.kt
  data/src/main/kotlin/com/signal/data/model/diagnosis/DiagnosisEntity.kt
  data/src/main/kotlin/com/signal/data/model/diagnosis/DiagnosisModel.kt
  data/src/main/kotlin/com/signal/data/repository/DiagnosisRepositoryImpl.kt
  domain/src/main/kotlin/com/signal/domain/entity/DiagnosisEntity.kt
  domain/src/main/kotlin/com/signal/domain/repository/DiagnosisRepository.kt
  presentation/src/main/java/com/signal/signal_android/DBInitializer.kt
  presentation/src/main/java/com/signal/signal_android/MainActivity.kt
  presentation/src/main/java/com/signal/signal_android/SignalApplication.kt
  presentation/src/main/java/com/signal/signal_android/feature/diagnosis/Diagnosis.kt
  presentation/src/main/java/com/signal/signal_android/feature/diagnosis/DiagnosisSideEffect.kt
  presentation/src/main/java/com/signal/signal_android/feature/diagnosis/DiagnosisState.kt
  presentation/src/main/java/com/signal/signal_android/feature/diagnosis/DiagnosisViewModel.kt
Labels: 기능 구현

#66 🔀 :: (#65) 마이페이지 뷰 수정
  presentation/src/main/java/com/signal/signal_android/feature/mypage/MyPage.kt
  presentation/src/main/res/values/strings.xml
Labels: 리팩토링

#67 🔀 :: (#60) 이미지 업로드 기능 구현
  data/src/main/kotlin/com/signal/data/api/ApiProvider.kt
  data/src/main/kotlin/com/signal/data/api/AttachmentApi.kt
  data/src/main/kotlin/com/signal/data/api/FeedApi.kt
  data/src/main/kotlin/com/signal/data/api/SignalUrl.kt
  data/src/main/kotlin/com/signal/data/datasource/feed/FeedDataSource.kt
  data/src/main/kotlin/com/signal/data/datasource/feed/FeedDataSourceImpl.kt
  data/src/main/kotlin/com/signal/data/datasource/file/AttachmentDataSource.kt
  data/src/main/kotlin/com/signal/data/datasource/file/AttachmentDataSourceImpl.kt
  data/src/main/kotlin/com/signal/data/model/attachment/UploadFileResponse.kt
  data/src/main/kotlin/com/signal/data/model/feed/request/PostRequest.kt
  data/src/main/kotlin/com/signal/data/repository/AttachmentRepositoryImpl.kt
  data/src/main/kotlin/com/signal/data/repository/FeedRepositoryImpl.kt
  data/src/main/kotlin/com/signal/data/util/FileUtil.kt
  domain/src/main/kotlin/com/signal/domain/entity/UploadFileEntity.kt
  domain/src/main/kotlin/com/signal/domain/repository/AttachmentRepository.kt
  domain/src/main/kotlin/com/signal/domain/repository/FeedRepository.kt
  presentation/src/main/java/com/signal/signal_android/SignalApplication.kt
  presentation/src/main/java/com/signal/signal_android/feature/file/AttachmentSideEffect.kt
  presentation/src/main/java/com/signal/signal_android/feature/file/AttachmentState.kt
  presentation/src/main/java/com/signal/signal_android/feature/file/AttachmentViewModel.kt
  presentation/src/main/java/com/signal/signal_android/feature/main/feed/CreatePost.kt
  presentation/src/main/java/com/signal/signal_android/feature/main/feed/Feed.kt
  presentation/src/main/java/com/signal/signal_android/feature/main/feed/FeedState.kt
  presentation/src/main/java/com/signal/signal_android/feature/main/feed/FeedViewModel.kt
Labels: 기능 구현

#69 🔀 :: (#68) 자가진단 설문 수정
  presentation/src/main/java/com/signal/signal_android/feature/diagnosis/Diagnosis.kt
  presentation/src/main/res/values/strings.xml
Labels: 버그!, 리팩토링

#72 ⚡️ :: 앱 아이콘 설정
  presentation/src/main/ic_launcher-playstore.png
  presentation/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  presentation/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  presentation/src/main/res/mipmap-anydpi/ic_launcher.xml
  presentation/src/main/res/mipmap-anydpi/ic_launcher_round.xml
  presentation/src/main/res/mipmap-hdpi/ic_launcher.webp
  presentation/src/main/res/mipmap-hdpi/ic_launcher_foreground.webp
  presentation/src/main/res/mipmap-hdpi/ic_launcher_round.webp
  presentation/src/main/res/mipmap-mdpi/ic_launcher.webp
  presentation/src/main/res/mipmap-mdpi/ic_launcher_foreground.webp
  presentation/src/main/res/mipmap-mdpi/ic_launcher_round.webp
  presentation/src/main/res/mipmap-xhdpi/ic_launcher.webp
  presentation/src/main/res/mipmap-xhdpi/ic_launcher_foreground.webp
  presentation/src/main/res/mipmap-xhdpi/ic_launcher_round.webp
  presentation/src/main/res/mipmap-xxhdpi/ic_launcher.webp
  presentation/src/main/res/mipmap-xxhdpi/ic_launcher_foreground.webp
  presentation/src/main/res/mipmap-xxhdpi/ic_launcher_round.webp
  presentation/src/main/res/mipmap-xxxhdpi/ic_launcher.webp
  presentation/src/main/res/mipmap-xxxhdpi/ic_launcher_foreground.webp
  presentation/src/main/res/mipmap-xxxhdpi/ic_launcher_round.webp
  presentation/src/main/res/values/ic_launcher_background.xml
  presentation/src/main/res/values/strings.xml
Labels: 기능 구현

#73 🔀 :: (#70) 댓글 목록 조회 구현
  data/src/main/kotlin/com/signal/data/api/FeedApi.kt
  data/src/main/kotlin/com/signal/data/api/SignalUrl.kt
  data/src/main/kotlin/com/signal/data/datasource/feed/FeedDataSource.kt
  data/src/main/kotlin/com/signal/data/datasource/feed/FeedDataSourceImpl.kt
  data/src/main/kotlin/com/signal/data/model/feed/response/FetchPostCommentsResponse.kt
  data/src/main/kotlin/com/signal/data/repository/FeedRepositoryImpl.kt
  domain/src/main/kotlin/com/signal/domain/entity/PostCommentsEntity.kt
  domain/src/main/kotlin/com/signal/domain/repository/FeedRepository.kt
  presentation/src/main/java/com/signal/signal_android/feature/main/feed/CommentDialog.kt
  presentation/src/main/java/com/signal/signal_android/feature/main/feed/FeedDetails.kt
  presentation/src/main/java/com/signal/signal_android/feature/main/feed/FeedState.kt
  presentation/src/main/java/com/signal/signal_android/feature/main/feed/FeedViewModel.kt
Labels: 기능 구현

#80 🔀 :: (#79) 자가진단 최근 일자 기능 구현
  data/src/main/kotlin/com/signal/data/datasource/diagnosis/LocalDiagnosisDataSource.kt
  data/src/main/kotlin/com/signal/data/datasource/diagnosis/LocalDiagnosisDataSourceImpl.kt
  data/src/main/kotlin/com/signal/data/datasource/user/local/LocalUserDataSource.kt
  data/src/main/kotlin/com/signal/data/datasource/user/local/LocalUserDataSourceImpl.kt
  data/src/main/kotlin/com/signal/data/repository/DiagnosisRepositoryImpl.kt
  data/src/main/kotlin/com/signal/data/repository/UserRepositoryImpl.kt
  data/src/main/kotlin/com/signal/data/util/PreferenceManager.kt
  domain/src/main/kotlin/com/signal/domain/repository/DiagnosisRepository.kt
  domain/src/main/kotlin/com/signal/domain/repository/UserRepository.kt
  domain/src/main/kotlin/com/signal/domain/usecase/users/GetAccountIdUseCase.kt
  domain/src/main/kotlin/com/signal/domain/usecase/users/SaveAccountIdUseCase.kt
  presentation/src/main/java/com/signal/signal_android/SignalApplication.kt
  presentation/src/main/java/com/signal/signal_android/feature/diagnosis/DiagnosisComplete.kt
  presentation/src/main/java/com/signal/signal_android/feature/diagnosis/DiagnosisState.kt
  presentation/src/main/java/com/signal/signal_android/feature/diagnosis/DiagnosisViewModel.kt
  presentation/src/main/java/com/signal/signal_android/feature/main/home/Home.kt
  presentation/src/main/java/com/signal/signal_android/feature/main/home/HomeSideEffect.kt
  presentation/src/main/java/com/signal/signal_android/feature/main/home/HomeState.kt
  presentation/src/main/java/com/signal/signal_android/feature/main/home/HomeViewModel.kt
  presentation/src/main/java/com/signal/signal_android/feature/signin/SignInViewModel.kt
Labels: 기능 구현, 리팩토링

#84 🔀 :: (#75) 피드 필터 변경
  data/src/main/kotlin/com/signal/data/api/FeedApi.kt
  data/src/main/kotlin/com/signal/data/api/SignalUrl.kt
  data/src/main/kotlin/com/signal/data/datasource/feed/FeedDataSource.kt
  data/src/main/kotlin/com/signal/data/datasource/feed/FeedDataSourceImpl.kt
  data/src/main/kotlin/com/signal/data/model/feed/response/FetchPostsResponse.kt
  data/src/main/kotlin/com/signal/data/repository/FeedRepositoryImpl.kt
  data/src/main/kotlin/com/signal/data/util/ExceptionHandler.kt
  domain/src/main/kotlin/com/signal/domain/PostsEntity.kt
  domain/src/main/kotlin/com/signal/domain/enums/Tag.kt
  domain/src/main/kotlin/com/signal/domain/repository/FeedRepository.kt
  presentation/src/main/java/com/signal/signal_android/SignalApplication.kt
  presentation/src/main/java/com/signal/signal_android/designsystem/component/Header.kt
  presentation/src/main/java/com/signal/signal_android/feature/diagnosis/Diagnosis.kt
  presentation/src/main/java/com/signal/signal_android/feature/main/diary/AllDiary.kt
  presentation/src/main/java/com/signal/signal_android/feature/main/diary/DiaryDetail.kt
  presentation/src/main/java/com/signal/signal_android/feature/main/feed/CreatePost.kt
  presentation/src/main/java/com/signal/signal_android/feature/main/feed/Feed.kt
  presentation/src/main/java/com/signal/signal_android/feature/main/feed/FeedDetails.kt
  presentation/src/main/java/com/signal/signal_android/feature/main/feed/FeedState.kt
  presentation/src/main/java/com/signal/signal_android/feature/main/feed/FeedViewModel.kt
  presentation/src/main/java/com/signal/signal_android/feature/main/feed/Report.kt
  presentation/src/main/java/com/signal/signal_android/feature/main/reservation/CreateReservation.kt
  presentation/src/main/java/com/signal/signal_android/feature/main/reservation/Hospital.kt
  presentation/src/main/java/com/signal/signal_android/feature/main/reservation/Reservation.kt
  presentation/src/main/res/drawable/ic_filter.xml
  presentation/src/main/res/values/strings.xml
Labels: 리팩토링

#86 🔀 :: (#85) 회원가입 피드백 반영
  presentation/src/main/java/com/signal/signal_android/feature/signup/SignUpState.kt
  presentation/src/main/java/com/signal/signal_android/feature/signup/SignUpUser.kt
  presentation/src/main/java/com/signal/signal_android/feature/signup/SignUpViewModel.kt
  presentation/src/main/res/values/strings.xml
Labels: 리팩토링

#87 🔀 :: (#78) 댓글 작성 구현
  data/src/main/kotlin/com/signal/data/api/FeedApi.kt
  data/src/main/kotlin/com/signal/data/api/SignalUrl.kt
  data/src/main/kotlin/com/signal/data/datasource/feed/FeedDataSource.kt
  data/src/main/kotlin/com/signal/data/datasource/feed/FeedDataSourceImpl.kt
  data/src/main/kotlin/com/signal/data/model/feed/request/CreateCommentRequest.kt
  data/src/main/kotlin/com/signal/data/model/feed/request/CreatePostRequest.kt
  data/src/main/kotlin/com/signal/data/model/feed/response/FetchCommentsResponse.kt
  data/src/main/kotlin/com/signal/data/repository/FeedRepositoryImpl.kt
  domain/src/main/kotlin/com/signal/domain/entity/PostCommentsEntity.kt
  domain/src/main/kotlin/com/signal/domain/repository/FeedRepository.kt
  presentation/src/main/java/com/signal/signal_android/feature/main/feed/CommentDialog.kt
  presentation/src/main/java/com/signal/signal_android/feature/main/feed/Feed.kt
  presentation/src/main/java/com/signal/signal_android/feature/main/feed/FeedDetails.kt
  presentation/src/main/java/com/signal/signal_android/feature/main/feed/FeedSideEffect.kt
  presentation/src/main/java/com/signal/signal_android/feature/main/feed/FeedState.kt
  presentation/src/main/java/com/signal/signal_android/feature/main/feed/FeedViewModel.kt
Labels: 기능 구현

#88 🔀 :: (#63) 고민 일기 기능 구현
  data/src/main/kotlin/com/signal/data/api/ApiProvider.kt
  data/src/main/kotlin/com/signal/data/api/DiaryApi.kt
  data/src/main/kotlin/com/signal/data/api/SignalUrl.kt
  data/src/main/kotlin/com/signal/data/datasource/diary/DiaryDataSource.kt
  data/src/main/kotlin/com/signal/data/datasource/diary/DiaryDataSourceImpl.kt
  data/src/main/kotlin/com/signal/data/model/diary/CreateDiaryRequest.kt
  data/src/main/kotlin/com/signal/data/model/diary/FetchDiariesResponse.kt
  data/src/main/kotlin/com/signal/data/model/diary/FetchDiaryDetailsResponse.kt
  data/src/main/kotlin/com/signal/data/model/diary/FetchMonthDiariesResponse.kt
  data/src/main/kotlin/com/signal/data/model/feed/response/FetchPostsResponse.kt
  data/src/main/kotlin/com/signal/data/repository/DiaryRepositoryImpl.kt
  data/src/main/kotlin/com/signal/data/repository/FeedRepositoryImpl.kt
  domain/src/main/kotlin/com/signal/domain/entity/DiariesEntity.kt
  domain/src/main/kotlin/com/signal/domain/entity/DiaryDetailsEntity.kt
  domain/src/main/kotlin/com/signal/domain/entity/MonthDiaryEntity.kt
  domain/src/main/kotlin/com/signal/domain/entity/PostsEntity.kt
  domain/src/main/kotlin/com/signal/domain/enums/Emotion.kt
  domain/src/main/kotlin/com/signal/domain/repository/DiaryRepository.kt
  domain/src/main/kotlin/com/signal/domain/repository/FeedRepository.kt
  presentation/src/main/java/com/signal/signal_android/SignalApplication.kt
  presentation/src/main/java/com/signal/signal_android/feature/main/diary/AllDiary.kt
  presentation/src/main/java/com/signal/signal_android/feature/main/diary/CreateDiary.kt
  presentation/src/main/java/com/signal/signal_android/feature/main/diary/Diary.kt
  presentation/src/main/java/com/signal/signal_android/feature/main/diary/DiaryDetail.kt
  presentation/src/main/java/com/signal/signal_android/feature/main/diary/DiarySideEffect.kt
  presentation/src/main/java/com/signal/signal_android/feature/main/diary/DiaryState.kt
  presentation/src/main/java/com/signal/signal_android/feature/main/diary/DiaryViewModel.kt
  presentation/src/main/java/com/signal/signal_android/feature/main/diary/Emotion.kt
  presentation/src/main/java/com/signal/signal_android/feature/main/feed/Feed.kt
  presentation/src/main/java/com/signal/signal_android/feature/main/feed/FeedState.kt
  presentation/src/main/java/com/signal/signal_android/feature/main/feed/FeedViewModel.kt
  presentation/src/main/java/com/signal/signal_android/navigation/MainNavigation.kt
  presentation/src/main/res/drawable/ic_delete.xml
  presentation/src/main/res/values/strings.xml
Labels: 기능 구현

#95 🔀 :: (#77) 피드 삭제 구현
  data/src/main/kotlin/com/signal/data/api/FeedApi.kt
  data/src/main/kotlin/com/signal/data/api/SignalUrl.kt
  data/src/main/kotlin/com/signal/data/datasource/feed/FeedDataSource.kt
  data/src/main/kotlin/com/signal/data/datasource/feed/FeedDataSourceImpl.kt
  data/src/main/kotlin/com/signal/data/model/feed/response/FetchPostsResponse.kt
  data/src/main/kotlin/com/signal/data/repository/FeedRepositoryImpl.kt
  domain/src/main/kotlin/com/signal/domain/entity/PostsEntity.kt
  domain/src/main/kotlin/com/signal/domain/repository/FeedRepository.kt
  presentation/src/main/java/com/signal/signal_android/feature/main/feed/Feed.kt
  presentation/src/main/java/com/signal/signal_android/feature/main/feed/FeedDetails.kt
  presentation/src/main/java/com/signal/signal_android/feature/main/feed/FeedViewModel.kt
Labels: 기능 구현

#98 🔀 :: (#97) 상세보기 명세 수정
  data/src/main/kotlin/com/signal/data/api/SignalUrl.kt
  data/src/main/kotlin/com/signal/data/model/feed/response/FetchPostDetailsResponse.kt
  domain/src/main/kotlin/com/signal/domain/entity/PostDetailsEntity.kt
  presentation/src/main/java/com/signal/signal_android/feature/main/feed/Feed.kt
  presentation/src/main/java/com/signal/signal_android/feature/main/feed/FeedDetails.kt
  presentation/src/main/java/com/signal/signal_android/feature/main/feed/FeedState.kt
  presentation/src/main/java/com/signal/signal_android/feature/main/feed/FeedViewModel.kt
Labels: 리팩토링

#99 🔀 :: (#82) 업적 퍼블리싱
  presentation/src/main/java/com/signal/signal_android/SignalApp.kt
  presentation/src/main/java/com/signal/signal_android/SignalApplication.kt
  presentation/src/main/java/com/signal/signal_android/feature/achievement/MoreAchievements.kt
  presentation/src/main/java/com/signal/signal_android/feature/main/Main.kt
  presentation/src/main/java/com/signal/signal_android/feature/mypage/MyPage.kt
  presentation/src/main/java/com/signal/signal_android/feature/mypage/MyPageSideEffect.kt
  presentation/src/main/java/com/signal/signal_android/feature/mypage/MyPageState.kt
  presentation/src/main/java/com/signal/signal_android/feature/mypage/MyPageViewModel.kt
  presentation/src/main/java/com/signal/signal_android/navigation/MainNavigation.kt
  presentation/src/main/java/com/signal/signal_android/navigation/NavigationRoute.kt
  presentation/src/main/res/drawable/ic_coin.png
  presentation/src/main/res/drawable/ic_coin_1k.png
  presentation/src/main/res/values/strings.xml
Labels: 기능 구현

#100 🔀 :: (#96) 우울증 수치 차트 연동
  data/src/main/kotlin/com/signal/data/dao/DiagnosisDao.kt
  data/src/main/kotlin/com/signal/data/database/SignalDatabase.kt
  data/src/main/kotlin/com/signal/data/datasource/diagnosis/LocalDiagnosisDataSource.kt
  data/src/main/kotlin/com/signal/data/datasource/diagnosis/LocalDiagnosisDataSourceImpl.kt
  data/src/main/kotlin/com/signal/data/model/diagnosis/DiagnosisHistoryModel.kt
  data/src/main/kotlin/com/signal/data/repository/DiagnosisRepositoryImpl.kt
  domain/src/main/kotlin/com/signal/domain/entity/DiagnosisHistoryEntity.kt
  domain/src/main/kotlin/com/signal/domain/enums/ChartViewType.kt
  domain/src/main/kotlin/com/signal/domain/repository/DiagnosisRepository.kt
  domain/src/main/kotlin/com/signal/domain/usecase/users/GetDiagnosisHistoriesUseCase.kt
  presentation/src/main/java/com/signal/signal_android/SignalApplication.kt
  presentation/src/main/java/com/signal/signal_android/feature/diagnosis/Diagnosis.kt
  presentation/src/main/java/com/signal/signal_android/feature/diagnosis/DiagnosisComplete.kt
  presentation/src/main/java/com/signal/signal_android/feature/diagnosis/DiagnosisState.kt
  presentation/src/main/java/com/signal/signal_android/feature/diagnosis/DiagnosisViewModel.kt
  presentation/src/main/java/com/signal/signal_android/feature/main/home/Home.kt
  presentation/src/main/java/com/signal/signal_android/feature/main/home/HomeState.kt
  presentation/src/main/java/com/signal/signal_android/feature/main/home/HomeViewModel.kt
Labels: 기능 구현

#101 🔀 :: (#94) 피드 조회 리팩토링
  data/src/main/kotlin/com/signal/data/api/SignalUrl.kt
  data/src/main/kotlin/com/signal/data/model/feed/request/CreatePostRequest.kt
  data/src/main/kotlin/com/signal/data/repository/FeedRepositoryImpl.kt
  domain/src/main/kotlin/com/signal/domain/repository/FeedRepository.kt
  presentation/src/main/java/com/signal/signal_android/feature/main/feed/Feed.kt
  presentation/src/main/java/com/signal/signal_android/feature/main/feed/FeedState.kt
  presentation/src/main/java/com/signal/signal_android/feature/main/feed/FeedViewModel.kt
Labels: 기능 구현

#102 🔀 :: (#76) 피드 수정 구현
  data/src/main/kotlin/com/signal/data/api/FeedApi.kt
  data/src/main/kotlin/com/signal/data/datasource/feed/FeedDataSource.kt
  data/src/main/kotlin/com/signal/data/datasource/feed/FeedDataSourceImpl.kt
  data/src/main/kotlin/com/signal/data/repository/FeedRepositoryImpl.kt
  domain/src/main/kotlin/com/signal/domain/repository/FeedRepository.kt
  presentation/src/main/java/com/signal/signal_android/SignalApp.kt
  presentation/src/main/java/com/signal/signal_android/feature/main/Main.kt
  presentation/src/main/java/com/signal/signal_android/feature/main/feed/CreatePost.kt
  presentation/src/main/java/com/signal/signal_android/feature/main/feed/Feed.kt
  presentation/src/main/java/com/signal/signal_android/feature/main/feed/FeedState.kt
  presentation/src/main/java/com/signal/signal_android/feature/main/feed/FeedViewModel.kt
  presentation/src/main/java/com/signal/signal_android/navigation/MainNavigation.kt
  presentation/src/main/res/values/strings.xml
Labels: 기능 구현, 리팩토링

#104 🔀 :: (#103) 우울증 그래프 초기 설정
  presentation/src/main/java/com/signal/signal_android/feature/main/home/Home.kt
  presentation/src/main/res/values/strings.xml
Labels: 기능 구현

#106 🔀 :: (#105) 게시글 상세에서 수정, 삭제 기능 구현
  presentation/src/main/java/com/signal/signal_android/feature/main/feed/Feed.kt
  presentation/src/main/java/com/signal/signal_android/feature/main/feed/FeedDetails.kt
  presentation/src/main/java/com/signal/signal_android/feature/main/feed/FeedSideEffect.kt
  presentation/src/main/java/com/signal/signal_android/feature/main/feed/FeedViewModel.kt
  presentation/src/main/java/com/signal/signal_android/navigation/MainNavigation.kt
Labels: 기능 구현

#107 🔀 :: (#74) 피드 페이징 구현
  presentation/src/main/java/com/signal/signal_android/feature/main/feed/CreatePost.kt
  presentation/src/main/java/com/signal/signal_android/feature/main/feed/Feed.kt
  presentation/src/main/java/com/signal/signal_android/feature/main/feed/FeedState.kt
  presentation/src/main/java/com/signal/signal_android/feature/main/feed/FeedViewModel.kt
Labels: 기능 구현

#109 🔀 :: (#92) 그래프 색상 변경
  presentation/src/main/java/com/signal/signal_android/feature/main/home/Home.kt
Labels: 기능 구현

#108 🔀 :: (#93) 명언 기능 구현
  data/build.gradle.kts
  data/src/main/kotlin/com/signal/data/dao/MyPageDao.kt
  data/src/main/kotlin/com/signal/data/database/SignalDatabase.kt
  data/src/main/kotlin/com/signal/data/datasource/user/local/LocalUserDataSource.kt
  data/src/main/kotlin/com/signal/data/datasource/user/local/LocalUserDataSourceImpl.kt
  data/src/main/kotlin/com/signal/data/model/mypage/FamousSayingModel.kt
  data/src/main/kotlin/com/signal/data/repository/UserRepositoryImpl.kt
  domain/src/main/kotlin/com/signal/domain/entity/FamousSayingEntity.kt
  domain/src/main/kotlin/com/signal/domain/repository/UserRepository.kt
  domain/src/main/kotlin/com/signal/domain/usecase/users/AddFamousSayingUseCase.kt
  domain/src/main/kotlin/com/signal/domain/usecase/users/GetFamousSayingUseCase.kt
  presentation/build.gradle.kts
  presentation/src/main/java/com/signal/signal_android/DBInitializer.kt
  presentation/src/main/java/com/signal/signal_android/SignalApplication.kt
  presentation/src/main/java/com/signal/signal_android/feature/main/Main.kt
  presentation/src/main/java/com/signal/signal_android/feature/mypage/MyPage.kt
  presentation/src/main/java/com/signal/signal_android/feature/mypage/MyPageState.kt
  presentation/src/main/java/com/signal/signal_android/feature/mypage/MyPageViewModel.kt
  presentation/src/main/res/values/strings.xml
Labels: 기능 구현

#114 🔀 :: (#113) 고민일기 작성 수정
  data/src/main/kotlin/com/signal/data/api/ApiProvider.kt
  data/src/main/kotlin/com/signal/data/api/DiaryApi.kt
  data/src/main/kotlin/com/signal/data/api/SignalUrl.kt
  data/src/main/kotlin/com/signal/data/datasource/diary/DiaryDataSource.kt
  data/src/main/kotlin/com/signal/data/datasource/diary/DiaryDataSourceImpl.kt
  data/src/main/kotlin/com/signal/data/model/diary/CreateDiaryRequest.kt
  data/src/main/kotlin/com/signal/data/model/diary/FetchDiariesResponse.kt
  data/src/main/kotlin/com/signal/data/model/diary/FetchDiaryDetailsResponse.kt
  data/src/main/kotlin/com/signal/data/model/diary/FetchMonthDiariesResponse.kt
  data/src/main/kotlin/com/signal/data/repository/DiaryRepositoryImpl.kt
  domain/src/main/kotlin/com/signal/domain/entity/DiariesEntity.kt
  domain/src/main/kotlin/com/signal/domain/entity/MonthDiaryEntity.kt
  domain/src/main/kotlin/com/signal/domain/repository/DiaryRepository.kt
  presentation/src/main/java/com/signal/signal_android/feature/main/Main.kt
  presentation/src/main/java/com/signal/signal_android/feature/main/diary/AllDiary.kt
  presentation/src/main/java/com/signal/signal_android/feature/main/diary/CreateDiary.kt
  presentation/src/main/java/com/signal/signal_android/feature/main/diary/Diary.kt
  presentation/src/main/java/com/signal/signal_android/feature/main/diary/DiaryDetail.kt
  presentation/src/main/java/com/signal/signal_android/feature/main/diary/DiarySideEffect.kt
  presentation/src/main/java/com/signal/signal_android/feature/main/diary/DiaryState.kt
  presentation/src/main/java/com/signal/signal_android/feature/main/diary/DiaryViewModel.kt
  presentation/src/main/java/com/signal/signal_android/navigation/MainNavigation.kt
Labels: 버그!, 리팩토링

#112 🔀 :: (#111) 차트 보기 기능 구현
  data/src/main/kotlin/com/signal/data/model/diagnosis/DiagnosisHistoryModel.kt
  domain/src/main/kotlin/com/signal/domain/entity/DiagnosisHistoryEntity.kt
  presentation/src/main/java/com/signal/signal_android/designsystem/chart/Marker.kt
  presentation/src/main/java/com/signal/signal_android/feature/diagnosis/DiagnosisViewModel.kt
  presentation/src/main/java/com/signal/signal_android/feature/main/home/DiagnosisHistoryUiModel.kt
  presentation/src/main/java/com/signal/signal_android/feature/main/home/Home.kt
  presentation/src/main/java/com/signal/signal_android/feature/main/home/HomeState.kt
  presentation/src/main/java/com/signal/signal_android/feature/main/home/HomeViewModel.kt
  presentation/src/main/res/drawable/ic_information.xml
  presentation/src/main/res/values/strings.xml
Labels: 기능 구현

#118 🔀 :: (#116) 추천 목록 퍼블리싱
  domain/src/main/kotlin/com/signal/domain/enums/RecommendType.kt
  presentation/src/main/java/com/signal/signal_android/SignalApp.kt
  presentation/src/main/java/com/signal/signal_android/feature/main/Main.kt
  presentation/src/main/java/com/signal/signal_android/feature/main/diary/AllDiary.kt
  presentation/src/main/java/com/signal/signal_android/feature/main/recommend/Recommend.kt
  presentation/src/main/java/com/signal/signal_android/feature/main/recommend/RecommendDetails.kt
  presentation/src/main/java/com/signal/signal_android/feature/main/recommend/Recommends.kt
  presentation/src/main/java/com/signal/signal_android/navigation/MainNavigation.kt
  presentation/src/main/java/com/signal/signal_android/navigation/NavigationRoute.kt
  presentation/src/main/res/drawable/ic_play.xml
  presentation/src/main/res/values/strings.xml
Labels: 기능 구현

#119 🔀 :: (#81) 진료 예약 기능 구현
  data/src/main/kotlin/com/signal/data/api/ApiProvider.kt
  data/src/main/kotlin/com/signal/data/api/ReservationApi.kt
  data/src/main/kotlin/com/signal/data/api/SignalUrl.kt
  data/src/main/kotlin/com/signal/data/datasource/reservation/ReservationDataSource.kt
  data/src/main/kotlin/com/signal/data/datasource/reservation/ReservationDataSourceImpl.kt
  data/src/main/kotlin/com/signal/data/model/reservation/CreateReservationRequest.kt
  data/src/main/kotlin/com/signal/data/model/reservation/FetchDayReservationsResponse.kt
  data/src/main/kotlin/com/signal/data/model/reservation/FetchHospitalsResponse.kt
  data/src/main/kotlin/com/signal/data/model/reservation/FetchReservationDetailsResponse.kt
  data/src/main/kotlin/com/signal/data/repository/ReservationRepositoryImpl.kt
  domain/src/main/kotlin/com/signal/domain/entity/FetchDayReservationsEntity.kt
  domain/src/main/kotlin/com/signal/domain/entity/FetchHospitalsEntity.kt
  domain/src/main/kotlin/com/signal/domain/entity/FetchReservationDetailsEntity.kt
  domain/src/main/kotlin/com/signal/domain/enums/ReservationStatus.kt
  domain/src/main/kotlin/com/signal/domain/repository/ReservationRepository.kt
  presentation/src/main/java/com/signal/signal_android/SignalApp.kt
  presentation/src/main/java/com/signal/signal_android/SignalApplication.kt
  presentation/src/main/java/com/signal/signal_android/feature/main/mypage/MyPage.kt
  presentation/src/main/java/com/signal/signal_android/feature/main/mypage/MyPageSideEffect.kt
  presentation/src/main/java/com/signal/signal_android/feature/main/mypage/MyPageState.kt
  presentation/src/main/java/com/signal/signal_android/feature/main/mypage/MyPageViewModel.kt
  presentation/src/main/java/com/signal/signal_android/feature/reservation/CreateReservation.kt
  presentation/src/main/java/com/signal/signal_android/feature/reservation/Hospital.kt
  presentation/src/main/java/com/signal/signal_android/feature/reservation/Reservation.kt
  presentation/src/main/java/com/signal/signal_android/feature/reservation/ReservationSideEffect.kt
  presentation/src/main/java/com/signal/signal_android/feature/reservation/ReservationState.kt
  presentation/src/main/java/com/signal/signal_android/feature/reservation/ReservationViewModel.kt
  presentation/src/main/java/com/signal/signal_android/navigation/MainNavigation.kt
  presentation/src/main/java/com/signal/signal_android/navigation/NavigationRoute.kt
  presentation/src/main/res/values/strings.xml
Labels: 기능 구현

#120 🔀 :: (#116) 추천 목록 조회 기능 구현
  data/src/main/kotlin/com/signal/data/api/ApiProvider.kt
  data/src/main/kotlin/com/signal/data/api/RecommendApi.kt
  data/src/main/kotlin/com/signal/data/api/SignalUrl.kt
  data/src/main/kotlin/com/signal/data/datasource/recommend/RecommendDataSource.kt
  data/src/main/kotlin/com/signal/data/datasource/recommend/RecommendDataSourceImpl.kt
  data/src/main/kotlin/com/signal/data/model/recommend/FetchRecommendsResponse.kt
  data/src/main/kotlin/com/signal/data/repository/RecommendRepositoryImpl.kt
  domain/src/main/kotlin/com/signal/domain/entity/RecommendsEntity.kt
  domain/src/main/kotlin/com/signal/domain/enums/Category.kt
  domain/src/main/kotlin/com/signal/domain/repository/RecommendRepository.kt
  presentation/src/main/java/com/signal/signal_android/SignalApplication.kt
  presentation/src/main/java/com/signal/signal_android/feature/main/recommend/Recommend.kt
  presentation/src/main/java/com/signal/signal_android/feature/main/recommend/RecommendSideEffect.kt
  presentation/src/main/java/com/signal/signal_android/feature/main/recommend/RecommendState.kt
  presentation/src/main/java/com/signal/signal_android/feature/main/recommend/RecommendViewModel.kt
  presentation/src/main/java/com/signal/signal_android/feature/main/recommend/Recommends.kt
  presentation/src/main/java/com/signal/signal_android/navigation/MainNavigation.kt
  presentation/src/main/java/com/signal/signal_android/navigation/NavigationRoute.kt
Labels: 기능 구현

#122 🔀 :: (#121) 추천 상세보기 기능 구현
  data/src/main/kotlin/com/signal/data/api/RecommendApi.kt
  data/src/main/kotlin/com/signal/data/api/SignalUrl.kt
  data/src/main/kotlin/com/signal/data/datasource/recommend/RecommendDataSource.kt
  data/src/main/kotlin/com/signal/data/datasource/recommend/RecommendDataSourceImpl.kt
  data/src/main/kotlin/com/signal/data/model/recommend/FetchRecommendDetailsResponse.kt
  data/src/main/kotlin/com/signal/data/model/recommend/FetchRecommendsResponse.kt
  data/src/main/kotlin/com/signal/data/repository/RecommendRepositoryImpl.kt
  domain/src/main/kotlin/com/signal/domain/entity/RecommendDetailsEntity.kt
  domain/src/main/kotlin/com/signal/domain/entity/RecommendsEntity.kt
  domain/src/main/kotlin/com/signal/domain/repository/RecommendRepository.kt
  presentation/src/main/java/com/signal/signal_android/feature/main/diary/AllDiary.kt
  presentation/src/main/java/com/signal/signal_android/feature/main/recommend/Recommend.kt
  presentation/src/main/java/com/signal/signal_android/feature/main/recommend/RecommendDetails.kt
  presentation/src/main/java/com/signal/signal_android/feature/main/recommend/RecommendState.kt
  presentation/src/main/java/com/signal/signal_android/feature/main/recommend/RecommendViewModel.kt
  presentation/src/main/java/com/signal/signal_android/feature/main/recommend/Recommends.kt
  presentation/src/main/res/values/strings.xml
Labels: 기능 구현

#124 🔀 :: (#123) 마이페이지 로컬 정보 저장 기능 구현
  data/src/main/kotlin/com/signal/data/dao/MyPageDao.kt
  data/src/main/kotlin/com/signal/data/database/SignalDatabase.kt
  data/src/main/kotlin/com/signal/data/datasource/user/local/LocalUserDataSource.kt
  data/src/main/kotlin/com/signal/data/datasource/user/local/LocalUserDataSourceImpl.kt
  data/src/main/kotlin/com/signal/data/model/mypage/UserInformationModel.kt
  data/src/main/kotlin/com/signal/data/repository/UserRepositoryImpl.kt
  domain/src/main/kotlin/com/signal/domain/repository/UserRepository.kt
  domain/src/main/kotlin/com/signal/domain/usecase/users/GetUserInformationUseCase.kt
  domain/src/main/kotlin/com/signal/domain/usecase/users/SetUserInformationUseCase.kt
  domain/src/main/kotlin/com/signal/domain/usecase/users/UpdateUserInformationUseCase.kt
  presentation/src/main/java/com/signal/signal_android/SignalApplication.kt
  presentation/src/main/java/com/signal/signal_android/feature/main/home/Home.kt
  presentation/src/main/java/com/signal/signal_android/feature/main/home/HomeState.kt
  presentation/src/main/java/com/signal/signal_android/feature/main/home/HomeViewModel.kt
  presentation/src/main/java/com/signal/signal_android/feature/main/mypage/MyPage.kt
  presentation/src/main/java/com/signal/signal_android/feature/main/mypage/MyPageViewModel.kt
Labels: 기능 구현

#130 🔀 :: (#129) 추천 이미지 옵셔널 처리
  data/src/main/kotlin/com/signal/data/model/recommend/FetchRecommendsResponse.kt
  domain/src/main/kotlin/com/signal/domain/entity/RecommendsEntity.kt
  presentation/src/main/java/com/signal/signal_android/feature/main/recommend/RecommendDetails.kt
Labels: 버그!

#128 🔀 :: (#127) 커뮤니티 로직 수정
  presentation/src/main/java/com/signal/signal_android/feature/main/feed/Feed.kt
  presentation/src/main/java/com/signal/signal_android/feature/main/feed/FeedState.kt
  presentation/src/main/java/com/signal/signal_android/feature/main/feed/FeedViewModel.kt
Labels: 리팩토링

#131 🔀 :: (#91) 시그널 포인트 및 업적 구현
  data/src/main/kotlin/com/signal/data/api/ApiProvider.kt
  data/src/main/kotlin/com/signal/data/api/CoinApi.kt
  data/src/main/kotlin/com/signal/data/api/SignalUrl.kt
  data/src/main/kotlin/com/signal/data/datasource/coin/CoinDataSource.kt
  data/src/main/kotlin/com/signal/data/datasource/coin/CoinDataSourceImpl.kt
  data/src/main/kotlin/com/signal/data/model/coin/CreateCoinRequest.kt
  data/src/main/kotlin/com/signal/data/model/coin/CreateCoinResponse.kt
  data/src/main/kotlin/com/signal/data/model/coin/FetchCoinsResponse.kt
  data/src/main/kotlin/com/signal/data/model/mypage/FetchUserInformationResponse.kt
  data/src/main/kotlin/com/signal/data/model/mypage/UserInformationModel.kt
  data/src/main/kotlin/com/signal/data/repository/CoinRepositoryImpl.kt
  domain/src/main/kotlin/com/signal/domain/entity/CoinsEntity.kt
  domain/src/main/kotlin/com/signal/domain/entity/CreateCoinEntity.kt
  domain/src/main/kotlin/com/signal/domain/entity/UserInformationEntity.kt
  domain/src/main/kotlin/com/signal/domain/enums/Coin.kt
  domain/src/main/kotlin/com/signal/domain/repository/CoinRepository.kt
  presentation/src/main/java/com/signal/signal_android/SignalApp.kt
  presentation/src/main/java/com/signal/signal_android/SignalApplication.kt
  presentation/src/main/java/com/signal/signal_android/feature/achievement/MoreAchievements.kt
  presentation/src/main/java/com/signal/signal_android/feature/coin/CoinDialog.kt
  presentation/src/main/java/com/signal/signal_android/feature/coin/CoinHistory.kt
  presentation/src/main/java/com/signal/signal_android/feature/coin/CoinSideEffect.kt
  presentation/src/main/java/com/signal/signal_android/feature/coin/CoinState.kt
  presentation/src/main/java/com/signal/signal_android/feature/coin/CoinViewModel.kt
  presentation/src/main/java/com/signal/signal_android/feature/main/Main.kt
  presentation/src/main/java/com/signal/signal_android/feature/main/diary/AllDiary.kt
  presentation/src/main/java/com/signal/signal_android/feature/main/diary/CreateDiary.kt
  presentation/src/main/java/com/signal/signal_android/feature/main/feed/CommentDialog.kt
  presentation/src/main/java/com/signal/signal_android/feature/main/feed/CreatePost.kt
  presentation/src/main/java/com/signal/signal_android/feature/main/feed/FeedDetails.kt
  presentation/src/main/java/com/signal/signal_android/feature/main/feed/FeedSideEffect.kt
  presentation/src/main/java/com/signal/signal_android/feature/main/feed/FeedViewModel.kt
  presentation/src/main/java/com/signal/signal_android/feature/main/mypage/MyPage.kt
  presentation/src/main/java/com/signal/signal_android/feature/main/mypage/MyPageState.kt
  presentation/src/main/java/com/signal/signal_android/feature/main/mypage/MyPageViewModel.kt
  presentation/src/main/java/com/signal/signal_android/feature/reservation/CreateReservation.kt
  presentation/src/main/java/com/signal/signal_android/navigation/MainNavigation.kt
  presentation/src/main/java/com/signal/signal_android/navigation/NavigationRoute.kt
  presentation/src/main/res/drawable/ic_my_page_coin.png
  presentation/src/main/res/values/strings.xml
Labels: 기능 구현
